name: GitHub Classroom Autograding

on:
  push:
    branches: [ main, master ]

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Classroom Autograder
        uses: education/autograding@v1